### PR TITLE
ADDED mini GFX lib 0.1

### PR DESCRIPTION
**Pull request by fgalliat**

### CODE REVIEW

**Comment by Legimet** [comment]
Thanks, I will take a look at it when I have some free time (probably 
Wednesday at the earliest).

**Comment by Legimet** [comment]
Sorry for the delay, but I'm planning to merge this soon.

(Also, could you add license headers to the files you created? You can copy them from the other files, but use your name.)

**Comment by fgalliat** [comment]
OK I'll do it soon...

I may also provide later an UART lib 'cause I post a way to Bluetoothize
the TI nSpire (
http://xtase.over-blog.com/ti-nspire-bluetooth-serial-interface)

**Comment by Legimet** [comment]
That looks interesting, I noticed your post on Omnimaga. You might want to 
post on CodeWalrus and TI-Planet for more visibility.

**Comment by fgalliat** [comment]
> could you add license headers to the files you created?
> --> done, commited & pushed ;) just take the latest version
> 
> You might want to post on CodeWalrus and TI-Planet for more visibility.
> ---> for TIPlanet it's already done, I don't know the site CodeWalrus so
> I'll try to find it

PS. thanks for these advices

**Comment by Legimet** [comment]
I merged this two days ago, sorry for repeatedly forgetting about this. Also, CodeWalrus is located at https://codewalr.us :)

**Pull request merged**
